### ISSUE TITLE
Environment variable for easier env detection

### ISSUE THREAD

**Issue by hudecsamuel** [mergado/mergado-apps#42]
At the begining of **AppCloud** there was **`MERGADO_APPCLOUD_APPSTAGE`** env variable to help with app  stage configuration.

Currently there is no such variable or none that i am avare of (tried `printenv`), but it would be realy useful.

**Comment by smuuf** [comment]
Are you trying `printenv` via SSH? Because `MERGADO_APPCLOUD_APPSTAGE` environment variable is being set by HTTP server and thus is not available in terminal session. Stage detection in terminal *(or command line tools, scripts and whatnot)* may be done via detection of app's directory path.

If app's path contains `.dev`, ie in `/srv/production/apps/app_logbook.dev/`, it is a `dev` stage. If it does not, it is a production stage.
