### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#62]
Please update PHP to 7.1 on AppCloud. It would be better to set PHP version per-app (it doesnt make sense to update very old apps).

**Comment by kluvi** [comment]
btw active support for 7.0 ends in 24days (1 more year of security support)

**Comment by smuuf** [comment]
This would *definitely* be a good-to-have thing.

Unfortunately the architecture of the first Appcloud doesn't allow safe, gradual transition from PHP `7.0` to PHP `7.1` on a *per-app* basis, since the version of PHP is shared amongst all apps present on Appcloud.

First, we need to know, whether all apps on AC are *in fact* ready for PHP 7.1. ***Only then would it be safe to upgrade PHP version.***

I've created an online poll, where *(since there are not so many of app vendors, yet)* vendors can, in a form of a *YES or NO vote*, communicate if their app is ready for PHP 7.1.

Run your tests, go through your app, and please tell us.
**Enter the name of your app as "your name".**

Poll is available here: https://doodle.com/poll/26qbz7dvknt2b88z
*Votes are anonymous; only we can see the names entered.*

**Comment by smuuf** [comment]
Ok, now I see that you voted *YES* as *one* of your apps; but you have more than one. What about the others? Could you maybe try and test them and then "vote some more"?

**Comment by smuuf** [comment]
PHP 7.1 has been present on Appcloud since 24th of January (as described here: https://forum.mergado.cz/t/novinky-v-platforme-pro-vyvojare/318/16). Closing.
