### ISSUE TITLE
Long-running app.disable hooks

### ISSUE THREAD

**Issue by kluvi** [mergado/mergado-apps#63]
When App has a lot of data in database (milions of records), it is sometimes impossible to delete all data in timeout limit.

**Comment by smuuf** [comment]
Currently Mergado waits for a response when `disabling` app *(the same as when it is being `enabled`)*. That's happening because we want to give the app some way to report eventual errors or other reasons why the process wasn't successfull.

At least this is the rationale behind such behaviour *(waiting for app's response)* when some app is being ***enabled***. Maybe this kind of waiting makes less sense when disabling an app...?
